backend = "glx";
vsync = true;

# Prevent tearing / glitches
#glx-no-stencil = true;
glx-copy-from-front = false;

# Don't break fullscreen apps (important for games)
unredir-if-possible = true;

# Basic visuals (light, safe)
shadow = true;
shadow-radius = 6;
shadow-opacity = 0.4;

fading = false;
