# NOTE: to reload the config, prees prefix + I

set -g cursor-style blinking-block

setw -g mouse on
setw -g mode-keys emacs

# window navigation
bind -n M-H previous-window
bind -n M-L next-window

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -s default-terminal 'xterm-256color'
set -ga terminal-overrides ",*:Tc"

set -g status-style "bg=#0a2540"

run -b '~/.tmux/plugins/tpm/tpm'

